#!/bin/sh
_CONDA_ROOT="C:/Users/M.Sabetta/Anaconda3/envs/test-automation"
# Copyright (C) 2012 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause
\. "$_CONDA_ROOT/etc/profile.d/conda.sh" || return $?
conda activate "$@"
